# Generated by Django 6.0.5 on 2026-06-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('location', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=200)),
                ('japanese_level', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('github_url', models.URLField()),
                ('linkedin_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('languages', 'Languages & Frameworks'), ('databases', 'Databases'), ('auth', 'Auth & Security'), ('queues', 'Task Queues'), ('testing', 'Testing'), ('devops', 'DevOps & Tools'), ('ai', 'AI / ML')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
    ]
